### PR TITLE
fix bottom space on forYou's NewsFeed last item

### LINKED ISSUE #204: [Bug]: forYou's NewsFeed has no space at the bottom of the last item
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

The NewsFeed of forYou does not leave spaces at the bottom of the last item.

if spaces are added, the user's visual experience may be better.

Consider simply adding contentPadding = PaddingValues(bottom = 16.dp).

### Relevant logcat output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by YvesKalume**
fix #204 by adding `8.dp` as padding at the bottom of the last item

Screenshot_20220808_161238

### CODE REVIEW

File: feature-foryou/src/main/java/com/google/samples/apps/nowinandroid/feature/foryou/ForYouScreen.kt [hunk 1]
```diff
@@ -219,7 +218,7 @@ fun ForYouScreen(
                     )
 
                     item {
-                        Spacer(Modifier.windowInsetsBottomHeight(WindowInsets.safeDrawing))
```
Comment (alexvanyo) [inline feature-foryou/src/main/java/com/google/samples/apps/nowinandroid/feature/foryou/ForYouScreen.kt:222]: We don't want to remove the insets support here, as otherwise cards could be obscured by the bottom insets when we're using the navigation rail instead of the navigation bar.

If we add another `Spacer` with the `8.dp` height that should fix the issue and avoid overlapping with insets!

**Review by alexvanyo — CHANGES_REQUESTED** [review]

File: feature-foryou/src/main/java/com/google/samples/apps/nowinandroid/feature/foryou/ForYouScreen.kt (hunk 1 above)
Comment (YvesKalume) [reply feature-foryou/src/main/java/com/google/samples/apps/nowinandroid/feature/foryou/ForYouScreen.kt:222]: Done

**Review by alexvanyo — APPROVED** [review]
Looks great! Would it be possible to update with the latest changes that were merged in? Thank you!

**Comment by YvesKalume** [comment]
Getting an error : error: failed to push some refs to 'https://github.com/YvesKalume/nowinandroid'
To https://github.com/YvesKalume/nowinandroid
!	refs/heads/main:refs/heads/main	[remote rejected] (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/Build.yaml` without `workflow` scope)

But my token has all permissions.

**Comment by alexvanyo** [comment]
Hmm, not sure how to help debug. If you're using GitHub's UI, maybe instead doing it locally would work? Or vice versa.
