### PR TITLE
Fix #1079: Update thumb movement range by thumb size, in app scrollbars

### LINKED ISSUE #1079: [Bug]: Scrollbar thumb position might be incorrect, because of a lot of content in LazyList
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

This is because when thumb size is the minimum size, thumb movement range will be incorrect.
This can be corrected by recalculating thumb movement range based on thumb size.

### Relevant logcat output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by oikvpqya**
**What I have done and why**
Update thumb movement range by thumb size, in app scrollbars

Fixes #1079

**Do tests pass?**
- [✓] Run local tests on `DemoDebug` variant: `./gradlew testDemoDebug`
- [✓] Check formatting: `./gradlew --init-script gradle/init.gradle.kts spotlessApply`

**Is this your first pull request?**
- [✓] [Sign the CLA](https://cla.developers.google.com/)
- [✓] Run `./tools/setup.sh`
- [✓] Import the code formatting style as explained in [the setup script](/tools/setup.sh#L40).

### CODE REVIEW

File: core/designsystem/src/main/kotlin/com/google/samples/apps/nowinandroid/core/designsystem/component/scrollbar/Scrollbar.kt [hunk 1]
```diff
@@ -91,6 +91,12 @@ class ScrollbarState {
      */
     val thumbMovedPercent
         get() = unpackFloat2(packedValue)
+
+    /**
+     * Returns the max distance the thumb can travel as a percentage of total track size
+     */
+    val thumbTrackSizePercent
+        get() = 1f - unpackFloat1(packedValue)
```
Comment (tunjid) [inline core/designsystem/src/main/kotlin/com/google/samples/apps/nowinandroid/core/designsystem/component/scrollbar/Scrollbar.kt:99]: Can you use `thumbSizePercent` here so its more readable?

**Review by tunjid — APPROVED** [review]
Thanks for the fix!
