### PR TITLE
Fix #1595 navigation to topic detail screen causes crash

### LINKED ISSUE #1595: [Bug]: DemoRelease runtime error on interest screen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Build variants: demoRelease
This happened after had been merged #1413 .

https://github.com/user-attachments/assets/00b26cca-bb92-4768-ae6c-ea44d0a88f65

It worked on 371e181b79ebcca4d7b38e24b800143025ae96f9.



### Relevant logcat output

```shell
2024-09-05 22:08:37.431  6315-6315  AndroidRuntime          <pre-initialized>                    E  FATAL EXCEPTION: main
                                                                                                    Process: com.google.samples.apps.nowinandroid.demo, PID: 6315
                                                                                                    X6.f: Serializer for class 'c' is not found.
                                                                                                    Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
                                                                                                    
                                                                                                    	at b7.b0.h(SourceFile:26)
                                                                                                    	at K3.a.N(SourceFile:13)
                                                                                                    	at b2.x.<init>(SourceFile:8)
                                                                                                    	at b2.A.<init>(SourceFile:26)
                                                                                                    	at H2.v.e(SourceFile:16)
                                                                                                    	at Z5.f.h(SourceFile:236)
                                                                                                    	at g0.a.a(SourceFile:44)
                                                                                                    	at g0.a.h(SourceFile:9)
                                                                                                    	at T.n.h(SourceFile:98)
                                                                                                    	at g0.a.a(SourceFile:44)
                                                                                                    	at g0.a.h(SourceFile:9)
                                                                                                    	at androidx.compose.animation.a.a(SourceFile:1523)
                                                                                                    	at androidx.compose.animation.a.e(SourceFile:230)
                                                                                                    	at androidx.compose.animation.a.b(SourceFile:170)
                                                                                                    	at androidx.compose.material3.adaptive.layout.a.a(SourceFile:291)
                                                                                                    	at Z5.f.h(SourceFile:69)
                                                                                                    	at g0.a.a(SourceFile:44)
                                                                                                    	at g0.a.h(SourceFile:9)
                                                                                                    	at T.F.i(SourceFile:251)
                                                                                                    	at g0.a.i(SourceFile:52)
                                                                                                    	at H.s0.i(SourceFile:1266)
                                                                                                    	at g0.a.i(SourceFile:52)
                                                                                                    	at T.H.h(SourceFile:303)
                                                                                                    	at g0.a.a(SourceFile:44)
                                                                                                    	at C.G.i(SourceFile:141)
                                                                                                    	at Y.p.E(SourceFile:451)
                                                                                                    	at Y.p.N(SourceFile:29)
                                                                                                    	at I0.e0.a(SourceFile:35)
                                                                                                    	at n7.d.T(SourceFile:591)
                                                                                                    	at T.E.i(SourceFile:43)
                                                                                                    	at Y.p.E(SourceFile:451)
                                                                                                    	at Y.p.L(SourceFile:137)
                                                                                                    	at Y.p.o(SourceFile:238)
                                                                                                    	at Y.p.D(SourceFile:30)
                                                                                                    	at Y.t.u(SourceFile:23)
                                                                                                    	at Y.t0.p(SourceFile:103)
                                                                                                    	at Y.r0.j(SourceFile:564)
                                                                                                    	at L0.d0.doFrame(SourceFile:34)
                                                                                                    	at L0.b0.doFrame(SourceFile:48)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:941)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8699)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                                                                                                    	Suppressed: Q6.g: [L0.e0@6b66b49, L0.D0@3d21c4e, x0{Cancelling}@76a016f, c0@f6c9e7c]
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dturner**
Fixes #1595 by `@Keep`ing a navigation route which is only used as a type parameter and a class reference, and is therefore removed during minification. This would cause a crash when navigating to the topic detail screen.

### CODE REVIEW

**Review by alexvanyo — APPROVED** [review]

File: app/src/main/kotlin/com/google/samples/apps/nowinandroid/ui/interests2pane/InterestsListDetailScreen.kt [hunk 1]
```diff
@@ -53,6 +54,8 @@ import java.util.UUID
 
 @Serializable internal object TopicPlaceholderRoute
```
Comment (alexvanyo) [inline app/src/main/kotlin/com/google/samples/apps/nowinandroid/ui/interests2pane/InterestsListDetailScreen.kt:55]: What's the reason that we have to `@Keep` the `DetailPaneNavHostRoute`, but not the `TopicPlaceholderRoute`?

Comment (dturner) [reply app/src/main/kotlin/com/google/samples/apps/nowinandroid/ui/interests2pane/InterestsListDetailScreen.kt:55]: I'm not overly familiar with the minification process but my guess is that because the instance of `TopicPlaceholderRoute` is [referenced here](https://github.com/android/nowinandroid/blob/main/app/src/main/kotlin/com/google/samples/apps/nowinandroid/ui/interests2pane/InterestsListDetailScreen.kt#L98) it is not removed. 

On the other hand, `DetailPaneNavHostRoute` is only used as a parameterized type, never as an actual instance, so is removed.
