### PR TITLE
Empty search text is added in recent searches problem fix.

### LINKED ISSUE #1222: [Bug]: Empty search text is added in recent searches.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

As you see below gif.
Empty search text is added in recent searches.
issue

### Relevant logcat output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jaehwa-Noh**
**What I have done and why**
Empty search is added in recent searches. It was unpredictable behavior. I fixed it.

• Add if statement to prevent insert empty query.
• Add blank text prevent keyboard hide and search.
• Add test code.

Fixes #1222 

keyboard

### CODE REVIEW

File: feature/search/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModel.kt [hunk 1]
```diff
@@ -103,10 +103,12 @@ class SearchViewModel @Inject constructor(
...
-        viewModelScope.launch {
-            recentSearchRepository.insertOrReplaceRecentSearch(searchQuery = query)
+        if (query.isNotBlank()) {
+            viewModelScope.launch {
+                recentSearchRepository.insertOrReplaceRecentSearch(searchQuery = query)
+            }
+            analyticsHelper.logEventSearchTriggered(query = query)
         }
-        analyticsHelper.logEventSearchTriggered(query = query)
     }
```
Comment (SimonMarquis) [inline feature/search/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModel.kt:112]: nit: cleaner with an early exit:

```kotlin
    fun onSearchTriggered(query: String) {
        if (query.isBlank()) return
        viewModelScope.launch {
            recentSearchRepository.insertOrReplaceRecentSearch(searchQuery = query)
        }
        analyticsHelper.logEventSearchTriggered(query = query)
    }
```

File: feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt [hunk 2]
```diff
@@ -128,4 +129,15 @@ class SearchViewModelTest {
...
+
+    @Test
+    fun emptySearchText_NotAddToRecentSearches() = runTest {
+        viewModel.onSearchTriggered("")
+
+        val recentSearchQueriesStream = getRecentQueryUseCase()
+        val recentSearchQueries = recentSearchQueriesStream.first()
+        val recentSearchQuery = recentSearchQueries.firstOrNull()
+
+        assertEquals(null, recentSearchQuery)
```
Comment (SimonMarquis) [inline feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt:141]:
```suggestion
        assertNull(recentSearchQuery)
```

File: feature/search/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModel.kt (hunk 1 above)
Comment (Jaehwa-Noh) [reply feature/search/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModel.kt:112]: Good suggestion. Thank you.

File: feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt [hunk 3]
```diff
@@ -33,9 +33,11 @@ import com.google.samples.apps.nowinandroid.feature.search.SearchResultUiState.E
 import com.google.samples.apps.nowinandroid.feature.search.SearchResultUiState.Loading
 import com.google.samples.apps.nowinandroid.feature.search.SearchResultUiState.SearchNotReady
 import kotlinx.coroutines.flow.collect
+import kotlinx.coroutines.flow.first
 import kotlinx.coroutines.launch
 import kotlinx.coroutines.test.UnconfinedTestDispatcher
 import kotlinx.coroutines.test.runTest
+import org.junit.Assert.assertNull
```
[the remark this answers is not in the document]
Comment (Jaehwa-Noh) [reply feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt:40]: > `import kotlin.test.assertNull` instead

Can I ask why I use import kotlin.test.assertNull?

[the remark this answers is not in the document]
Comment (Jaehwa-Noh) [reply feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt:40]: Oh, I got it. That was the reason I'd missed it. Thank you!

File: feature/search/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModel.kt [hunk 4]
```diff
@@ -57,7 +57,9 @@ class SearchViewModel @Inject constructor(
                     flowOf(SearchResultUiState.SearchNotReady)
                 } else {
                     searchQuery.flatMapLatest { query ->
-                        if (query.length < SEARCH_QUERY_MIN_LENGTH) {
+                        if ((query.length < SEARCH_QUERY_MIN_LENGTH)
+                                .or(query.isBlank())
+                        ) {
```
Comment (SimonMarquis) [inline feature/search/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModel.kt:62]: Don't over-use Kotlin extension functions where there is no need for it:

```suggestion
                        if (query.length < SEARCH_QUERY_MIN_LENGTH) || query.isBlank()) {
```

Also, what about simply trimming the query? This would take care of both cases, and make the `SEARCH_QUERY_MIN_LENGTH` more "correct"

File: feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt [hunk 5]
```diff
@@ -128,4 +130,41 @@ class SearchViewModelTest {
...
+
+        val recentSearchQueriesStream = getRecentQueryUseCase()
+        val recentSearchQueries = recentSearchQueriesStream.first()
+        val recentSearchQuery = recentSearchQueries.firstOrNull()
+
+        assertNull(recentSearchQuery)
+    }
+
+    @Test
+    fun stateIsEmptyQuery_withThreeWhiteSpacesSearchQuery() = runTest {
```
Comment (dturner) [inline feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt:146]: Test names should follow the given-when-then format. So in this case it should be: 

Given a search query with 3 spaces
Then the state is empty query

Which translates to a test name of `searchTextWithThreeSpaces_isEmptyQuery`

Comment (dturner) [inline feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt:146]:
```suggestion
    fun searchTextWithThreeSpaces_isEmptyQuery() = runTest {
```

File: feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt [hunk 6]
```diff
@@ -128,4 +130,41 @@ class SearchViewModelTest {
 
         collectJob.cancel()
     }
+
+    @Test
+    fun emptySearchText_NotAddToRecentSearches() = runTest {
```
Comment (dturner) [inline feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt:135]:
```suggestion
    fun emptySearchText_isNotAddedToRecentSearches() = runTest {
```

File: feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt [hunk 7]
```diff
@@ -128,4 +130,41 @@ class SearchViewModelTest {
...
+
+        viewModel.onSearchQueryChanged("   ")
+
+        assertIs<EmptyQuery>(viewModel.searchResultUiState.value)
+
+        collectJob.cancel()
+    }
+
+    @Test
+    fun stateIsEmptyQuery_withThreeWhiteSpacesAndOneLetterSearchQuery() = runTest {
```
Comment (dturner) [inline feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt:159]:
```suggestion
    fun searchTextWithThreeSpacesAndOneLetter_isEmptyQuery() = runTest {
```

**Review by dturner — DISMISSED** [review]
Thanks for doing this @Jaehwa-Noh, and for reviewing @SimonMarquis. Added some suggestions for test names.

File: feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt (hunk 5 above)
Comment (Jaehwa-Noh) [reply feature/search/src/test/kotlin/com/google/samples/apps/nowinandroid/feature/search/SearchViewModelTest.kt:146]: I'll change the test name from your suggestion.
Thank you.

**Review by keyboardsurfer — APPROVED** [review]

**Comment by keyboardsurfer** [comment]
Please address the changes requested by @dturner so we can proceed and merge this PR.

**Comment by Jaehwa-Noh** [comment]
@keyboardsurfer I've accepted all of @dturner 's suggestions. Kindly check this.
